before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq varnish libvarnishapi-dev
  - sudo npm install vows -g
  - npm install vows
language: node_js
node_js:
  - 0.8
  - 0.6
  - 0.9
install: node-waf configure build

